
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-gqapwd-com-v1beta1-mydaemonset
  failurePolicy: Fail
  name: mmydaemonset.kb.io
  rules:
  - apiGroups:
    - apps.gqapwd.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mydaemonsets
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-gqapwd-com-v1beta1-mydaemonset
  failurePolicy: Fail
  name: vmydaemonset.kb.io
  rules:
  - apiGroups:
    - apps.gqapwd.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mydaemonsets
  sideEffects: None
