# permissions for end users to edit mydaemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mydaemonset-editor-role
rules:
- apiGroups:
  - apps.gqapwd.com
  resources:
  - mydaemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.gqapwd.com
  resources:
  - mydaemonsets/status
  verbs:
  - get
